---
#
# ci/pipeline.yml
#
# Pipeline structure file for a BOSH Release pipeline
#
# DO NOT MAKE CHANGES TO THIS FILE.  Instead, modify
# ci/settings.yml and override what needs overridden.
# This uses spruce, so you have some options there.
#
# author:  James Hunt <james@niftylogic.com>
# created: 2016-03-30

meta:
  name:     (( param "Please name your pipeline" ))
  release:  (( grab meta.name ))
  target:   (( param "Please identify the name of the target Concourse CI" ))
  url:      (( param "Please specify the full url of the target Concourse CI" ))
  pipeline: (( concat meta.name "-boshrelease" ))
  manifest:
    path:   (( concat "manifests/" meta.name ".yml" ))

  git:
    email:  (( param "Please provide the git email for automated commits" ))
    name:   (( param "Please provide the git name for automated commits" ))

  image:
    name: starkandwayne/concourse
    tag: latest

  aws:
    bucket:      (( concat meta.pipeline "-pipeline" ))
    region_name: us-east-1
    access_key:  (( param "Please set your AWS Access Key ID for your pipeline S3 Bucket" ))
    secret_key:  (( param "Please set your AWS Secret Key ID for your pipeline S3 Bucket" ))

  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        (( param "Please specify the name of the user / organization that owns the Github repository" ))
    repo:         (( param "Please specify the name of the Github repository" ))
    branch:       master
    private_key:  (( param "Please generate an SSH Deployment Key for this repo and specify it here" ))
    access_token: (( param "Please generate a Personal Access Token to be used for creating github releases (do you have a ci-bot?)" ))

  bosh-lite:
    target:     (( param "Please specify the BOSH target URI for the bosh-lite to run test deployments against" ))
    cacert:     (( param "Please specify the BOSH Director Root CA cert" ))
    username:   admin
    password:   (( param "Please specify the BOSH Director admin password" ))
    deployment: (( concat meta.name "-testflight" ))

  shout:
    topic:    (( concat meta.name "-pipeline" ))
    url:      (( param "Please specify the Shout! endpoint" ))
    username: (( param "Please specify the Shout! operations username" ))
    password: (( param "Please specify the Shout! operations password" ))

    metadata:
      build-team-name:     $BUILD_TEAM_NAME
      build-job-name:      $BUILD_JOB_NAME
      build-pipeline-name: $BUILD_PIPELINE_NAME

    links:
      pipeline: (( concat meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME" ))
      build:    (( concat meta.shout.links.pipeline "/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME" ))

groups:
  - name: (( grab meta.pipeline ))
    jobs:
      - testflight
      - pre
      - rc
      - shipit
  - name: versioning
    jobs:
      - major
      - minor
      - patch
  - name: blobs
    jobs:
    - genesis
    - safe
    - esuf
    - cf
    - cf7
    - cf8
    - cloudfoundry-utils
    - bosh-backup-and-restore
    - bosh-cli
    - credhub-cli
    - fly
    - spruce
